name: Advanced Data Ingestion Pipeline

on:
  # Daily at 2 AM UTC (adjust timezone as needed)
  schedule:
    - cron: '0 2 * * *'
  
  # Manual trigger with options
  workflow_dispatch:
    inputs:
      endpoint:
        description: 'Specific endpoint to process'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - setlists
          - shows
          - songs
          - venues
          - jamcharts
          - latest
          - metadata
          - links
          - uploads
          - appearances
      force_refresh:
        description: 'Force refresh all data (ignore incremental updates)'
        required: false
        default: false
        type: boolean

jobs:
  ingest-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file
      run: |
        cat > .env << EOF
        SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        EMBEDDING_MODEL=text-embedding-3-small
        EMBEDDING_DIMENSIONS=1536
        CHAT_MODEL=gpt-4
        PORT=3000
        NODE_ENV=production
        LOG_LEVEL=info
        BAND_NAME=${{ secrets.BAND_NAME }}
        EOF
        
    - name: Run data ingestion
      run: |
        echo "🚀 Starting advanced data ingestion pipeline..."
        echo "📅 Run time: $(date)"
        echo "🎯 Target endpoint: ${{ github.event.inputs.endpoint || 'all' }}"
        echo "🔄 Force refresh: ${{ github.event.inputs.force_refresh || 'false' }}"
        
        # Run the ingestion
        npm test
        
        echo "✅ Data ingestion completed successfully!"
        
    - name: Generate summary report
      if: always()
      run: |
        echo "## 📊 Data Ingestion Report" >> $GITHUB_STEP_SUMMARY
        echo "**Run Time:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "**Target Endpoint:** ${{ github.event.inputs.endpoint || 'all' }}" >> $GITHUB_STEP_SUMMARY
        echo "**Force Refresh:** ${{ github.event.inputs.force_refresh || 'false' }}" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Check the [Supabase Dashboard](https://supabase.com/dashboard/project/jvvcxraopwbpewisiohu) for detailed results." >> $GITHUB_STEP_SUMMARY
        
    - name: Upload logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ingestion-logs-${{ github.run_number }}
        path: |
          *.log
          logs/
        retention-days: 7
