name: Test Data Ingestion

on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - quick
          - specific-endpoint
      endpoint:
        description: 'Specific endpoint to test (if applicable)'
        required: false
        default: 'setlists'
        type: choice
        options:
          - setlists
          - shows
          - songs
          - venues
          - jamcharts
          - latest
          - metadata
          - links
          - uploads
          - appearances

jobs:
  test-ingestion:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create environment file
      run: |
        cat > .env << EOF
        SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        EMBEDDING_MODEL=text-embedding-3-small
        EMBEDDING_DIMENSIONS=1536
        CHAT_MODEL=gpt-4
        PORT=3000
        NODE_ENV=production
        LOG_LEVEL=debug
        BAND_NAME=${{ secrets.BAND_NAME }}
        EOF
        
    - name: Run test
      run: |
        echo "🧪 Running ${{ github.event.inputs.test_type }} test..."
        echo "📅 Test time: $(date)"
        echo "🎯 Test type: ${{ github.event.inputs.test_type }}"
        
        if [ "${{ github.event.inputs.test_type }}" = "specific-endpoint" ]; then
          echo "🎯 Testing endpoint: ${{ github.event.inputs.endpoint }}"
        fi
        
        # Run the test
        npm test
        
        echo "✅ Test completed successfully!"
        
    - name: Generate test report
      if: always()
      run: |
        echo "## 🧪 Test Report" >> $GITHUB_STEP_SUMMARY
        echo "**Test Type:** ${{ github.event.inputs.test_type }}" >> $GITHUB_STEP_SUMMARY
        echo "**Test Time:** $(date)" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "View detailed results in the [Supabase Dashboard](https://supabase.com/dashboard/project/jvvcxraopwbpewisiohu)." >> $GITHUB_STEP_SUMMARY
